/**
 * `styles.css`'s custom properties, as data the universal tree resolves them from (decision 0015).
 *
 *   npm --workspace @jaira/universal run tokens          write src/cssTokens.generated.ts
 *   npm --workspace @jaira/universal run tokens -- --check   fail if it is stale (typecheck runs this)
 *
 * No page the universal tree draws carries the stylesheet: React Native has no cascade, and the app's
 * web page loads none either (`tokens.tsx`'s `Replayed`; only an island gets the sheet, scoped to its
 * own box). So a component cannot write `var(--accent)` and leave it to a browser: it needs the
 * declarations themselves, with enough of their selectors kept to replay the cascade — which palette,
 * which scheme, which subtree (`.sidebar`), and how specific. `cssTokens.ts` does the replaying.
 *
 * The stylesheet is held to these blocks and the islands' own rules by `pruneCss.mjs`, which keeps a
 * block this script reads even where no element carries its class any more.
 *
 * Only rules whose selector is one of these shapes are kept, and only their `--` declarations:
 *   :root  [data-theme="dark"]?  [data-palette="p"]? | :is([data-palette="a"], …)  ( .scope)?
 *   .scope                                   (component-local variables, e.g. `.pill-running`)
 * Anything else — a variable set inside `@media`, under a pseudo-class, on a compound selector — is
 * skipped, and listed by `--verbose`, because a universal component that needs one must say so by hand.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const CSS = fileURLToPath(new URL("../../app/src/renderer/styles.css", import.meta.url));
const OUT = fileURLToPath(new URL("../src/cssTokens.generated.ts", import.meta.url));

/** Top-level rules only; `@media`/`@supports` bodies are skipped whole (their braces nest). */
function* rules(css) {
  const text = css.replace(/\/\*[\s\S]*?\*\//g, "");
  let depth = 0;
  let start = 0;
  let selector = "";
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === "{") {
      if (depth === 0) {
        selector = text.slice(start, i).trim();
        start = i + 1;
      }
      depth++;
    } else if (c === "}") {
      depth--;
      if (depth === 0) {
        if (!selector.startsWith("@")) yield { selector, body: text.slice(start, i) };
        start = i + 1;
      }
    }
  }
}

function declarations(body) {
  const vars = {};
  for (const m of body.matchAll(/(--[\w-]+)\s*:\s*([^;]+?)\s*(?:;|$)/g)) vars[m[1].slice(2)] = m[2].replace(/\s+/g, " ");
  return vars;
}

/** Split a selector list on top-level commas (not the ones inside `:is(…)`). */
function split(list) {
  const out = [];
  let depth = 0;
  let from = 0;
  for (let i = 0; i < list.length; i++) {
    if (list[i] === "(") depth++;
    else if (list[i] === ")") depth--;
    else if (list[i] === "," && depth === 0) {
      out.push(list.slice(from, i).trim());
      from = i + 1;
    }
  }
  out.push(list.slice(from).trim());
  return out;
}

const ROOT = /^:root((?:\[data-(?:theme|palette)(?:="[\w-]+")?\]|:is\((?:\s*\[data-palette="[\w-]+"\]\s*,?)+\))*)(?:\s+\.([\w-]+))?$/;

function classify(selector) {
  const scopeOnly = /^\.([\w-]+)$/.exec(selector);
  if (scopeOnly) return { scope: scopeOnly[1], specificity: 10 };
  const m = ROOT.exec(selector);
  if (!m) return null;
  const quals = m[1] ?? "";
  const when = {};
  let specificity = 1;
  if (/\[data-theme="dark"\]/.test(quals)) {
    when.scheme = "dark";
    specificity += 10;
  } else if (/\[data-theme=/.test(quals)) return null;
  const is = /:is\(([^)]*)\)/.exec(quals);
  const named = [...(is ? is[1] : quals).matchAll(/\[data-palette="([\w-]+)"\]/g)].map((p) => p[1]);
  if (named.length > 0) {
    when.palette = named;
    specificity += 10;
  } else if (/\[data-palette\]/.test(quals)) {
    // `:root[data-palette]`: every named palette, none for classic (which removes the attribute).
    when.palette = "*";
    specificity += 10;
  }
  if (m[2] !== undefined) {
    when.scope = m[2];
    specificity += 10;
  }
  return { ...when, specificity };
}

const blocks = [];
const skipped = [];
let order = 0;
for (const { selector, body } of rules(readFileSync(CSS, "utf8"))) {
  const vars = declarations(body);
  if (Object.keys(vars).length === 0) continue;
  for (const one of split(selector)) {
    const c = classify(one);
    if (c === null) skipped.push(one);
    else blocks.push({ ...c, order: order++, vars });
  }
}

const palettes = [...new Set(blocks.flatMap((b) => (Array.isArray(b.palette) ? b.palette : [])))].sort();
const source =
  `// GENERATED by packages/universal/scripts/tokens.mjs from packages/app/src/renderer/styles.css.\n` +
  `// Do not edit: change the CSS and run \`npm --workspace @jaira/universal run tokens\`.\n\n` +
  `import type { TokenBlock } from "./cssTokens";\n\n` +
  `/** The named palettes; \`classic\` is the one with no \`data-palette\` at all. */\n` +
  `export const PALETTES = ${JSON.stringify(["classic", ...palettes])} as const;\n\n` +
  `export const BLOCKS: readonly TokenBlock[] = ${JSON.stringify(blocks, null, 1)};\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {}
  if (current !== source) {
    console.error("packages/universal/src/cssTokens.generated.ts is stale: run `npm --workspace @jaira/universal run tokens`");
    process.exit(1);
  }
} else {
  writeFileSync(OUT, source);
  console.log(`${blocks.length} blocks, ${palettes.length + 1} palettes → ${OUT}`);
}
if (process.argv.includes("--verbose")) console.log(`skipped selectors with variables:\n  ${skipped.join("\n  ")}`);
