import type { IpcChannel } from "@jaira/shared/browser";

/**
 * What a read-only remote client may ask (decision 0013, ruling 5: "read only as a v1 and interactive
 * as v2"). An ALLOWLIST, so a channel added to the contract later is refused until someone decides it
 * only reads. v2 drops the list.
 *
 * Three entries change something, and are here because the UI cannot be walked without them:
 * `project:open` (standing on a project; the spike's clients share the desktop's current project,
 * 0013 S2), `artifact:serve` (a grant to show an artifact that already exists), and `limits:watch` and
 * `file:release` (a subscription and a handle, both bookkeeping).
 */
const READS = new Set<IpcChannel>([
  "project:open",
  "project:inspect",
  "project:current",
  "project:list",
  "task:list",
  "task:all",
  "task:detail",
  "task:resumable",
  "task:conversation",
  "task:system",
  "task:inputSources",
  "task:changes",
  "board:view",
  "board:roots",
  "files:tree",
  "files:hiddenReport",
  "files:whyHidden",
  "state:view",
  "state:slots",
  "state:effective",
  "session:history",
  "session:view",
  "session:live",
  "run:records",
  "chat:thread",
  "log:list",
  "job:list",
  "job:output",
  "interaction:pending",
  "functions:pending",
  "approval:pending",
  "question:pending",
  "userEvent:pending",
  "remote:status",
  "workflow:browse",
  "workflow:read",
  "workflow:syncStatus",
  "schema:validate",
  "schema:check",
  "schema:detect",
  "file:read",
  "file:check",
  "file:definition",
  "file:references",
  "file:hover",
  "file:source",
  "file:release",
  "file:find",
  "uri:read",
  "artifact:serve",
  "artifact:list",
  "git:identity",
  "changeset:review",
  "permissionSets:read",
  "permissionSets:judgeReadOnly",
  "events:status",
  "notices:list",
  "history:size",
  "settings:read",
  "config:read",
  "executor:list",
  "availability:read",
  "model:parameters",
  "catalog:status",
  "limits:read",
  "limits:watch",
  "waiting:list",
  "secret:capabilities",
  "licenses:read",
]);

export const readsOnly = (channel: IpcChannel): boolean => READS.has(channel);
