// GENERATED by packages/universal/scripts/tokens.mjs from packages/app/src/renderer/styles.css.
// Do not edit: change the CSS and run `npm --workspace @jaira/universal run tokens`.

import type { TokenBlock } from "./cssTokens";

/** The named palettes; `classic` is the one with no `data-palette` at all. */
export const PALETTES = ["classic","blueprint","contrast","hairline","ink","pastel","pastel-rail","zinc"] as const;

export const BLOCKS: readonly TokenBlock[] = [
 {
  "specificity": 1,
  "order": 0,
  "vars": {
   "bg": "#f5f6f8",
   "panel": "#ffffff",
   "panel-2": "#eceff4",
   "line": "#d4dae3",
   "rule": "#c2cbd9",
   "rail-s": "55%",
   "rail-l": "44%",
   "text": "#1b2130",
   "dim": "#5c6779",
   "accent": "#2563c7",
   "ok": "#0f7a45",
   "warn": "#8a6100",
   "bad": "#c02c1f",
   "scrim": "rgba(24, 30, 42, 0.38)",
   "lift": "0 12px 32px rgba(24, 30, 42, 0.18)",
   "tok-string": "#0f7a45",
   "tok-number": "#8a4a00",
   "tok-keyword": "#8b2fa0",
   "tok-type": "#0a5f9e",
   "tok-hint": "#949cad",
   "panel-3": "#e2e7ef",
   "fill-accent": "#2563c7",
   "fill-accent-hover": "#1c56b4",
   "on-accent": "#ffffff",
   "fill-ghost-hover": "rgba(24, 30, 42, 0.06)",
   "fill-ghost-selected": "rgba(24, 30, 42, 0.1)",
   "sheen": "inset 0 1px 0 rgba(255, 255, 255, 0.2)",
   "p1": "#3f76d4",
   "p2": "#b57a1c",
   "p3": "#7d5fc7",
   "p0": "#737b8d"
  }
 },
 {
  "scheme": "dark",
  "specificity": 11,
  "order": 1,
  "vars": {
   "bg": "#0f1115",
   "panel": "#161922",
   "panel-2": "#1c2029",
   "line": "#262b36",
   "rule": "#3b4356",
   "rail-s": "62%",
   "rail-l": "68%",
   "text": "#e6e9ef",
   "dim": "#8b93a7",
   "accent": "#6ea8fe",
   "ok": "#57d38c",
   "warn": "#ffc857",
   "bad": "#ff6b6b",
   "scrim": "rgba(0, 0, 0, 0.55)",
   "lift": "0 18px 50px rgba(0, 0, 0, 0.5)",
   "tok-string": "#7ad39c",
   "tok-number": "#e0b070",
   "tok-keyword": "#d79bf0",
   "tok-type": "#7fc4f0",
   "tok-hint": "#5a6274",
   "panel-3": "#232833",
   "fill-accent": "#3f76d4",
   "fill-accent-hover": "#4b81dd",
   "on-accent": "#ffffff",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.055)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.1)",
   "sheen": "inset 0 1px 0 rgba(255, 255, 255, 0.18)",
   "p1": "#6e9df0",
   "p2": "#d7a145",
   "p3": "#a98ee6",
   "p0": "#8b93a7"
  }
 },
 {
  "specificity": 1,
  "order": 2,
  "vars": {
   "control-radius": "7px",
   "control-radius-sm": "6px",
   "control-pad": "3px 10px",
   "control-pad-sm": "2px 8px",
   "card-radius": "10px",
   "tint-accent": "color-mix(in srgb, var(--accent) 10%, transparent)",
   "tint-ok": "color-mix(in srgb, var(--ok) 10%, transparent)",
   "tint-warn": "color-mix(in srgb, var(--warn) 12%, transparent)",
   "tint-bad": "color-mix(in srgb, var(--bad) 10%, transparent)",
   "focus-ring": "color-mix(in srgb, var(--accent) 70%, transparent)",
   "font-app": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif",
   "font-data": "\"JetBrains Mono\", \"SF Mono\", \"SFMono-Regular\", Menlo, Consolas, ui-monospace, monospace",
   "size-app": "12.5px",
   "size-data": "12px",
   "size-editor": "var(--size-data)",
   "z-modal": "50",
   "z-toast": "60",
   "z-float": "100",
   "z-crash": "1000"
  }
 },
 {
  "specificity": 1,
  "order": 3,
  "vars": {
   "wco-left": "env(titlebar-area-x, 0px)",
   "wco-right": "calc(100vw - env(titlebar-area-x, 0px) - env(titlebar-area-width, 100vw))",
   "wco-height": "env(titlebar-area-height, 34px)"
  }
 },
 {
  "scope": "sg",
  "specificity": 10,
  "order": 4,
  "vars": {
   "wire-l": "52%",
   "wire-c": "0.15",
   "wire-idle": "oklch(var(--wire-l) 0 0)",
   "go-spine": "var(--rule)",
   "go-onward": "var(--accent)",
   "go-back": "var(--bad)",
   "go-abort": "var(--warn)"
  }
 },
 {
  "scheme": "dark",
  "scope": "sg",
  "specificity": 21,
  "order": 5,
  "vars": {
   "wire-l": "78%",
   "wire-c": "0.14"
  }
 },
 {
  "scope": "pill-running",
  "specificity": 10,
  "order": 6,
  "vars": {
   "pill-c": "var(--accent)"
  }
 },
 {
  "scope": "pill-waiting",
  "specificity": 10,
  "order": 7,
  "vars": {
   "pill-c": "var(--warn)"
  }
 },
 {
  "scope": "pill-error",
  "specificity": 10,
  "order": 8,
  "vars": {
   "pill-c": "var(--bad)"
  }
 },
 {
  "scope": "pill-warning",
  "specificity": 10,
  "order": 9,
  "vars": {
   "pill-c": "var(--warn)"
  }
 },
 {
  "scope": "pill-success",
  "specificity": 10,
  "order": 10,
  "vars": {
   "pill-c": "var(--ok)"
  }
 },
 {
  "scope": "cm-quote-line",
  "specificity": 10,
  "order": 11,
  "vars": {
   "md-inset": "10px"
  }
 },
 {
  "scope": "logs",
  "specificity": 10,
  "order": 12,
  "vars": {
   "log-cols": "11ch 5ch 22ch minmax(0, 1fr) 92px",
   "log-indent": "calc(10px + 11ch + 5ch + 22ch + 24px)"
  }
 },
 {
  "scope": "logs-dated",
  "specificity": 10,
  "order": 13,
  "vars": {
   "log-cols": "10ch 11ch 5ch 22ch minmax(0, 1fr) 92px",
   "log-indent": "calc(10px + 10ch + 11ch + 5ch + 22ch + 32px)"
  }
 },
 {
  "specificity": 1,
  "order": 14,
  "vars": {
   "ws-read": "#2f8a9e",
   "ws-search": "#6b5bd6",
   "ws-write": "#b0721a",
   "ws-run": "#3d7a4c",
   "ws-web": "#2f6fb5",
   "ws-tool": "#a8508a"
  }
 },
 {
  "scheme": "dark",
  "specificity": 11,
  "order": 15,
  "vars": {
   "ws-read": "#6cc3d6",
   "ws-search": "#a99cff",
   "ws-write": "#e0a656",
   "ws-run": "#7ccf8e",
   "ws-web": "#7fb2f0",
   "ws-tool": "#e08cc6"
  }
 },
 {
  "scope": "ws-chip",
  "specificity": 10,
  "order": 16,
  "vars": {
   "ws-h": "var(--tok-hint)"
  }
 },
 {
  "scope": "ws-k-think",
  "specificity": 10,
  "order": 17,
  "vars": {
   "ws-h": "var(--accent)"
  }
 },
 {
  "scope": "ws-k-read",
  "specificity": 10,
  "order": 18,
  "vars": {
   "ws-h": "var(--ws-read)"
  }
 },
 {
  "scope": "ws-k-search",
  "specificity": 10,
  "order": 19,
  "vars": {
   "ws-h": "var(--ws-search)"
  }
 },
 {
  "scope": "ws-k-write",
  "specificity": 10,
  "order": 20,
  "vars": {
   "ws-h": "var(--ws-write)"
  }
 },
 {
  "scope": "ws-k-run",
  "specificity": 10,
  "order": 21,
  "vars": {
   "ws-h": "var(--ws-run)"
  }
 },
 {
  "scope": "ws-k-git",
  "specificity": 10,
  "order": 22,
  "vars": {
   "ws-h": "var(--ws-run)"
  }
 },
 {
  "scope": "ws-k-web",
  "specificity": 10,
  "order": 23,
  "vars": {
   "ws-h": "var(--ws-web)"
  }
 },
 {
  "scope": "ws-k-agent",
  "specificity": 10,
  "order": 24,
  "vars": {
   "ws-h": "var(--ws-tool)"
  }
 },
 {
  "scope": "ws-k-tool",
  "specificity": 10,
  "order": 25,
  "vars": {
   "ws-h": "var(--ws-tool)"
  }
 },
 {
  "scope": "ws-k-wait",
  "specificity": 10,
  "order": 26,
  "vars": {
   "ws-h": "var(--warn)"
  }
 },
 {
  "scope": "rail",
  "specificity": 10,
  "order": 27,
  "vars": {
   "rail-cap": "34px"
  }
 },
 {
  "scope": "hid-box",
  "specificity": 10,
  "order": 28,
  "vars": {
   "hid-cols": "minmax(8rem, 12rem) minmax(0, 1fr) 6.5rem 2.6rem"
  }
 },
 {
  "palette": [
   "ink"
  ],
  "specificity": 11,
  "order": 29,
  "vars": {
   "bg": "#f5f6fa",
   "panel": "#ffffff",
   "panel-2": "#eef0f6",
   "panel-3": "#e5e8f1",
   "line": "#e0e3ec",
   "rule": "#c5cadb",
   "text": "#121526",
   "dim": "#5a5f7a",
   "accent": "#4a4fd1",
   "fill-accent": "#4a4fd1",
   "fill-accent-hover": "#3f44bd",
   "ok": "#13794a",
   "warn": "#8f5f00",
   "bad": "#c4302b",
   "fill-ghost-hover": "rgba(18, 21, 38, 0.05)",
   "fill-ghost-selected": "rgba(18, 21, 38, 0.09)",
   "chrome": "#171a2e",
   "track": "#eceef5",
   "track-edge": "transparent",
   "tile": "#ffffff",
   "tile-edge": "#dfe2ec",
   "tile-shadow": "0 1px 2px rgba(18, 21, 48, 0.07)",
   "tile-shadow-hi": "0 3px 10px rgba(18, 21, 48, 0.12)"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "ink"
  ],
  "specificity": 21,
  "order": 30,
  "vars": {
   "bg": "#0f1017",
   "panel": "#171923",
   "panel-2": "#141620",
   "panel-3": "#1e2130",
   "line": "#242838",
   "rule": "#363b52",
   "text": "#e8e9f3",
   "dim": "#8c90ab",
   "accent": "#9ea2ff",
   "fill-accent": "#5a5fe0",
   "fill-accent-hover": "#6a6fea",
   "ok": "#5fd49a",
   "warn": "#f2c35b",
   "bad": "#ff7b72",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.05)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.09)",
   "chrome": "#08091a",
   "track": "#13151e",
   "track-edge": "transparent",
   "tile": "#181b27",
   "tile-edge": "#262a3b",
   "tile-shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.04), 0 1px 2px rgba(0, 0, 0, 0.5)",
   "tile-shadow-hi": "inset 0 1px 0 rgba(255, 255, 255, 0.05), 0 4px 12px rgba(0, 0, 0, 0.55)"
  }
 },
 {
  "palette": [
   "ink"
  ],
  "scope": "sidebar",
  "specificity": 21,
  "order": 31,
  "vars": {
   "panel": "color-mix(in srgb, #ffffff 7%, var(--chrome))",
   "panel-2": "var(--chrome)",
   "panel-3": "color-mix(in srgb, #ffffff 11%, var(--chrome))",
   "line": "color-mix(in srgb, #ffffff 10%, var(--chrome))",
   "rule": "color-mix(in srgb, #ffffff 18%, var(--chrome))",
   "text": "#eceefa",
   "dim": "#9ca1c4",
   "accent": "#b3b6ff",
   "ok": "#6fd6a0",
   "warn": "#f3c464",
   "bad": "#ff8a80",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.06)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.1)",
   "tint-accent": "color-mix(in srgb, #b3b6ff 20%, transparent)",
   "tint-ok": "color-mix(in srgb, #6fd6a0 12%, transparent)",
   "tint-warn": "color-mix(in srgb, #f3c464 14%, transparent)",
   "tint-bad": "color-mix(in srgb, #ff8a80 12%, transparent)"
  }
 },
 {
  "palette": [
   "hairline"
  ],
  "specificity": 11,
  "order": 32,
  "vars": {
   "bg": "#ffffff",
   "panel": "#ffffff",
   "panel-2": "#f7f8fa",
   "panel-3": "#f2f4f7",
   "line": "#e3e6eb",
   "rule": "#cdd2da",
   "text": "#111827",
   "dim": "#5b6474",
   "fill-ghost-hover": "rgba(17, 24, 39, 0.04)",
   "fill-ghost-selected": "rgba(17, 24, 39, 0.07)",
   "chrome": "#ffffff",
   "track": "#ffffff",
   "track-edge": "#e3e6eb",
   "tile": "#ffffff",
   "tile-edge": "#e3e6eb",
   "tile-shadow": "0 0 #0000",
   "tile-shadow-hi": "0 0 #0000"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "hairline"
  ],
  "specificity": 21,
  "order": 33,
  "vars": {
   "bg": "#0d0f13",
   "panel": "#0d0f13",
   "panel-2": "#15181e",
   "panel-3": "#1a1e25",
   "line": "#232831",
   "rule": "#363d4a",
   "text": "#e7eaf0",
   "dim": "#8d95a6",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.04)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.08)",
   "chrome": "#0d0f13",
   "track": "#0d0f13",
   "track-edge": "#232831",
   "tile": "#0d0f13",
   "tile-edge": "#2a303a",
   "tile-shadow": "0 0 #0000",
   "tile-shadow-hi": "0 0 #0000"
  }
 },
 {
  "palette": [
   "contrast"
  ],
  "specificity": 11,
  "order": 34,
  "vars": {
   "bg": "#ffffff",
   "panel": "#ffffff",
   "panel-2": "#f0f0f0",
   "panel-3": "#e6e6e6",
   "line": "#8c8c8c",
   "rule": "#141414",
   "text": "#000000",
   "dim": "#3a3a3a",
   "accent": "#0040c8",
   "fill-accent": "#0040c8",
   "fill-accent-hover": "#00329e",
   "ok": "#0a6b2f",
   "warn": "#7a4d00",
   "bad": "#b00d0d",
   "fill-ghost-hover": "rgba(0, 0, 0, 0.06)",
   "fill-ghost-selected": "rgba(0, 0, 0, 0.11)",
   "chrome": "#ffffff",
   "track": "#ffffff",
   "track-edge": "#141414",
   "tile": "#ffffff",
   "tile-edge": "#141414",
   "tile-shadow": "2px 2px 0 #141414",
   "tile-shadow-hi": "3px 3px 0 #141414"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "contrast"
  ],
  "specificity": 21,
  "order": 35,
  "vars": {
   "bg": "#000000",
   "panel": "#000000",
   "panel-2": "#141414",
   "panel-3": "#1f1f1f",
   "line": "#6e6e6e",
   "rule": "#ededed",
   "text": "#ffffff",
   "dim": "#c4c4c4",
   "accent": "#7fb2ff",
   "fill-accent": "#2f6fe0",
   "fill-accent-hover": "#4a84ea",
   "ok": "#5fe08f",
   "warn": "#ffd166",
   "bad": "#ff7070",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.08)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.14)",
   "chrome": "#000000",
   "track": "#000000",
   "track-edge": "#ededed",
   "tile": "#000000",
   "tile-edge": "#ededed",
   "tile-shadow": "2px 2px 0 #ededed",
   "tile-shadow-hi": "3px 3px 0 #ededed"
  }
 },
 {
  "palette": [
   "blueprint"
  ],
  "specificity": 11,
  "order": 36,
  "vars": {
   "bg": "#f7faff",
   "panel": "#ffffff",
   "panel-2": "#eef4fd",
   "panel-3": "#e2ecfa",
   "line": "#b9cdea",
   "rule": "#6f93c7",
   "text": "#0f2f5e",
   "dim": "#4e6d98",
   "accent": "#d9480f",
   "fill-accent": "#d9480f",
   "fill-accent-hover": "#bb3c0a",
   "on-accent": "#ffffff",
   "ok": "#1b7a4a",
   "warn": "#9a6400",
   "bad": "#c0271d",
   "fill-ghost-hover": "rgba(15, 47, 94, 0.05)",
   "fill-ghost-selected": "rgba(15, 47, 94, 0.09)",
   "chrome": "#0f3b7a",
   "track": "transparent",
   "track-edge": "#6f93c7",
   "tile": "#ffffff",
   "tile-edge": "#6f93c7",
   "tile-shadow": "0 0 #0000",
   "tile-shadow-hi": "0 0 #0000",
   "grid": "rgba(15, 59, 122, 0.07)"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "blueprint"
  ],
  "specificity": 21,
  "order": 37,
  "vars": {
   "bg": "#0f3b7a",
   "panel": "#134487",
   "panel-2": "#0d3570",
   "panel-3": "#1a4f97",
   "line": "#3e68a6",
   "rule": "#9bb7de",
   "text": "#f2f7ff",
   "dim": "#b3cae9",
   "accent": "#ffe066",
   "fill-accent": "#f2c500",
   "fill-accent-hover": "#ffd21f",
   "on-accent": "#10213d",
   "ok": "#7cf0b0",
   "warn": "#ffb86b",
   "bad": "#ff9a9a",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.07)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.13)",
   "chrome": "#0b2f63",
   "track": "transparent",
   "track-edge": "#9bb7de",
   "tile": "#174a8f",
   "tile-edge": "#9bb7de",
   "tile-shadow": "0 0 #0000",
   "tile-shadow-hi": "0 0 #0000",
   "grid": "rgba(255, 255, 255, 0.08)"
  }
 },
 {
  "palette": [
   "blueprint"
  ],
  "scope": "sidebar",
  "specificity": 21,
  "order": 38,
  "vars": {
   "panel": "color-mix(in srgb, #ffffff 8%, var(--chrome))",
   "panel-2": "var(--chrome)",
   "panel-3": "color-mix(in srgb, #ffffff 12%, var(--chrome))",
   "line": "color-mix(in srgb, #ffffff 16%, var(--chrome))",
   "rule": "color-mix(in srgb, #ffffff 30%, var(--chrome))",
   "text": "#f2f7ff",
   "dim": "#b3cae9",
   "accent": "#ffe066",
   "ok": "#7cf0b0",
   "warn": "#ffb86b",
   "bad": "#ff9a9a",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.07)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.12)",
   "tint-accent": "color-mix(in srgb, #ffe066 18%, transparent)",
   "tint-ok": "color-mix(in srgb, #7cf0b0 12%, transparent)",
   "tint-warn": "color-mix(in srgb, #ffb86b 14%, transparent)",
   "tint-bad": "color-mix(in srgb, #ff9a9a 12%, transparent)"
  }
 },
 {
  "palette": [
   "pastel",
   "pastel-rail"
  ],
  "specificity": 11,
  "order": 39,
  "vars": {
   "bg": "#fbfaff",
   "panel": "#ffffff",
   "panel-2": "#f5f2ff",
   "panel-3": "#ece7fb",
   "line": "#ebe7f5",
   "rule": "#d2cce6",
   "text": "#2b2640",
   "dim": "#6e6887",
   "accent": "#6d4aff",
   "fill-accent": "#6d4aff",
   "fill-accent-hover": "#5c3ae8",
   "ok": "#1f8a4c",
   "warn": "#9a6200",
   "bad": "#d02f55",
   "fill-ghost-hover": "rgba(43, 38, 64, 0.04)",
   "fill-ghost-selected": "rgba(43, 38, 64, 0.08)",
   "chrome": "#f5f2ff",
   "track": "#f5f2ff",
   "track-edge": "transparent",
   "tile": "#ffffff",
   "tile-edge": "transparent",
   "tile-shadow": "0 1px 3px rgba(60, 40, 120, 0.1)",
   "tile-shadow-hi": "0 4px 12px rgba(60, 40, 120, 0.14)"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "pastel",
   "pastel-rail"
  ],
  "specificity": 21,
  "order": 40,
  "vars": {
   "bg": "#1e1e2e",
   "panel": "#24273a",
   "panel-2": "#1b1b29",
   "panel-3": "#2b2c40",
   "line": "#313244",
   "rule": "#45475a",
   "text": "#cdd6f4",
   "dim": "#a6adc8",
   "accent": "#cba6f7",
   "fill-accent": "#8c5fd6",
   "fill-accent-hover": "#9a6de0",
   "ok": "#a6e3a1",
   "warn": "#f9e2af",
   "bad": "#f38ba8",
   "fill-ghost-hover": "rgba(205, 214, 244, 0.05)",
   "fill-ghost-selected": "rgba(205, 214, 244, 0.09)",
   "chrome": "#181825",
   "track": "#1b1b29",
   "track-edge": "transparent",
   "tile": "#2a2b3d",
   "tile-edge": "#3a3b52",
   "tile-shadow": "0 1px 3px rgba(0, 0, 0, 0.4)",
   "tile-shadow-hi": "0 4px 12px rgba(0, 0, 0, 0.5)"
  }
 },
 {
  "palette": [
   "pastel-rail"
  ],
  "specificity": 11,
  "order": 41,
  "vars": {
   "chrome": "#2b2640"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "pastel-rail"
  ],
  "specificity": 21,
  "order": 42,
  "vars": {
   "chrome": "#11111b"
  }
 },
 {
  "palette": [
   "pastel-rail"
  ],
  "scope": "sidebar",
  "specificity": 21,
  "order": 43,
  "vars": {
   "panel": "color-mix(in srgb, #ffffff 7%, var(--chrome))",
   "panel-2": "var(--chrome)",
   "panel-3": "color-mix(in srgb, #ffffff 11%, var(--chrome))",
   "line": "color-mix(in srgb, #ffffff 11%, var(--chrome))",
   "rule": "color-mix(in srgb, #ffffff 20%, var(--chrome))",
   "text": "#ece8fb",
   "dim": "#b4acd6",
   "accent": "#c9b6ff",
   "ok": "#a6e3a1",
   "warn": "#f9e2af",
   "bad": "#f7a1b8",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.06)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.1)",
   "tint-accent": "color-mix(in srgb, #c9b6ff 22%, transparent)",
   "tint-ok": "color-mix(in srgb, #a6e3a1 12%, transparent)",
   "tint-warn": "color-mix(in srgb, #f9e2af 14%, transparent)",
   "tint-bad": "color-mix(in srgb, #f7a1b8 12%, transparent)"
  }
 },
 {
  "palette": [
   "zinc"
  ],
  "specificity": 11,
  "order": 44,
  "vars": {
   "bg": "#fcfcfc",
   "panel": "#ffffff",
   "panel-2": "#fafafa",
   "panel-3": "#f4f4f5",
   "line": "#e4e4e7",
   "rule": "#d4d4d8",
   "text": "#27272a",
   "dim": "#71717a",
   "accent": "#2150e0",
   "fill-accent": "#2150e0",
   "fill-accent-hover": "#1a43c4",
   "ok": "#047857",
   "warn": "#b45309",
   "bad": "#b91c1c",
   "fill-ghost-hover": "rgba(24, 24, 27, 0.04)",
   "fill-ghost-selected": "rgba(24, 24, 27, 0.07)",
   "chrome": "#fafafa",
   "track": "#fdfdfd",
   "track-edge": "#e4e4e7",
   "tile": "#ffffff",
   "tile-edge": "#e4e4e7",
   "tile-shadow": "0 1px 2px rgba(0, 0, 0, 0.05)",
   "tile-shadow-hi": "0 2px 6px rgba(0, 0, 0, 0.08)"
  }
 },
 {
  "scheme": "dark",
  "palette": [
   "zinc"
  ],
  "specificity": 21,
  "order": 45,
  "vars": {
   "bg": "#0a0a0a",
   "panel": "#121212",
   "panel-2": "#0f0f0f",
   "panel-3": "#171717",
   "line": "#1f1f1f",
   "rule": "#2e2e2e",
   "text": "#f5f5f5",
   "dim": "#8f8f8f",
   "accent": "#7c9cff",
   "fill-accent": "#3d6ef2",
   "fill-accent-hover": "#4f7cf5",
   "ok": "#34d399",
   "warn": "#fbbf24",
   "bad": "#f87171",
   "fill-ghost-hover": "rgba(255, 255, 255, 0.04)",
   "fill-ghost-selected": "rgba(255, 255, 255, 0.07)",
   "chrome": "#000000",
   "track": "#0f0f0f",
   "track-edge": "#1f1f1f",
   "tile": "#141414",
   "tile-edge": "#262626",
   "tile-shadow": "0 0 #0000",
   "tile-shadow-hi": "0 2px 8px rgba(0, 0, 0, 0.6)"
  }
 },
 {
  "specificity": 1,
  "order": 46,
  "vars": {
   "lane-1": "#f06a8a",
   "lane-2": "#3d9df2",
   "lane-3": "#34b36b",
   "lane-4": "#e8a21c",
   "lane-5": "#9b6cf0",
   "lane-6": "#1fa8a0",
   "lane-pct": "16%",
   "lane-ink": "62%",
   "lane-deep": "#1a1530"
  }
 },
 {
  "scheme": "dark",
  "specificity": 11,
  "order": 47,
  "vars": {
   "lane-1": "#f5a3b7",
   "lane-2": "#89b4fa",
   "lane-3": "#a6e3a1",
   "lane-4": "#f9e2af",
   "lane-5": "#cba6f7",
   "lane-6": "#94e2d5",
   "lane-pct": "13%",
   "lane-ink": "100%"
  }
 },
 {
  "scope": "um-accent",
  "specificity": 10,
  "order": 48,
  "vars": {
   "um-c": "var(--accent)"
  }
 },
 {
  "scope": "um-warn",
  "specificity": 10,
  "order": 49,
  "vars": {
   "um-c": "var(--warn)"
  }
 },
 {
  "scope": "um-bad",
  "specificity": 10,
  "order": 50,
  "vars": {
   "um-c": "var(--bad)"
  }
 },
 {
  "scope": "um-none",
  "specificity": 10,
  "order": 51,
  "vars": {
   "um-c": "var(--rule)"
  }
 },
 {
  "specificity": 1,
  "order": 52,
  "vars": {
   "um-teal": "#2f9e8f"
  }
 }
];
